export enum textTypes{

        TITLE_BOLD = "TITLE_BOLD", //24px
        TITLE_SEMI_BOLD = "TITLE_SEMI_BOLD", //24px
        TITLE_REGUALR = "TITLE_REGUALR",
        TITLE_LIGHT = "TITLE_LIGHT",
        SUB_TITLE_BOLD = "SUB_TITLE_BOLD",//20px
        SUB_TITLE_SEMI_BOLD = "SUB_TITLE_SEMI_BOLD",//20px
        SUB_TITLE_REGUALR = "SUB_TITLE_REGUALR",
        SUB_TITLE_LIGHT = "SUB_TITLE_LIGHT",
        PARAGRAPH_BOLD = "PARAGRAPH_BOLD",
        PARAGRAPH_SEMI_BOLD = "PARAGRAPH_SEMI_BOLD",
        PARAGRAPH_REGUALR = "PARAGRAPH_REGUALR",//14px
        PARAGRAPH_LIGHT = "PARAGRAPH_LIGHT",
        BUTTON_BOLD = "BUTTON_BOLD",
        BUTTON_SEMI_BOLD = "BUTTON_SEMI_BOLD",
        BUTTON_REGUALR = "BUTTON_REGUALR",//18px
        BUTTON_LIGHT = "BUTTON_LIGHT",
        PARAGRAPH_SMALL_BOLD = "PARAGRAPH_SMALL_BOLD",//10px
        PARAGRAPH_SMALL_SEMI_BOLD = "PARAGRAPH_SMALL_SEMI_BOLD",//10px
        PARAGRAPH_SMALL_REGUALR = "PARAGRAPH_SMALL_REGUALR",
        PARAGRAPH_SMALL_LIGHT = "PARAGRAPH_SMALL_LIGHT",

}